#!/usr/bin/env Rscript

# =============================================================================
# PESTFLY — Step 5: Random Forest origin-tracing validation
# =============================================================================
#
# Purpose
# -------
# Step 5 provides an independent machine-learning corroboration of the Step 4
# hierarchical SNP-based origin assignment.
#
# Step 4 remains the primary origin-tracing step.
# Step 5 is an orthogonal validation layer.
#
# Step 5 trains Random Forest classifiers on reference samples using the SNP
# matrices generated by Step 3, then:
#
#   1. evaluates reference classification performance by repeated stratified
#      k-fold cross-validation;
#
#   2. predicts query/intercept samples independently of the Step 4 Bayesian
#      multi-K assignment;
#
#   3. reports whether Random Forest predictions support, contradict, or remain
#      uncertain relative to the Step 4 interpretation.
#
# =============================================================================
# Conceptual relationship with Steps 4 and 4b
# =============================================================================
#
# Step 4:
#   Main hierarchical Bayesian-like likelihood assignment.
#   Uses multi-K stability, posterior probability, posterior gap, global K
#   agreement, and large-K tail agreement.
#
# Step 4b:
#   Leave-one-out validation of the Step 4 assignment logic on reference samples.
#
# Step 5:
#   Independent Random Forest validation.
#
# Random Forest does not use the Step 4 multi-K likelihood model. Instead, it
# learns classification rules from the same Step 3 SNP matrices and evaluates
# whether the same origin signal is recoverable with a different statistical
# framework.
#
# Therefore:
#
#   - concordance between Step 4 and Step 5 supports the assignment;
#   - discordance should be inspected, especially for subregion-level calls;
#   - Step 5 should not overrule Step 4 automatically.
#
# =============================================================================
# Default panels
# =============================================================================
#
#   P1: macroregion_3 Africa vs Asia
#   P2: subregion within Africa
#   P3: subregion within Asia
#
# P4 population-level assignment is not used in the default workflow.
#
# Interpretation:
#
#   - P1 RF predictions are relevant for all query samples.
#   - P2 RF predictions should only be interpreted for samples assigned to Africa
#     by Step 4.
#   - P3 RF predictions should only be interpreted for samples assigned to Asia
#     by Step 4.
#
# =============================================================================
# Inputs
# =============================================================================
#
# Required:
#
#   results/01_qc/metadata_clean.tsv
#   results/02_snp_panels/panels/<panel_id>/snp_matrix.rds
#   results/02_snp_panels/panels/<panel_id>/snp_map.tsv
#
# Optional:
#
#   results/04_origin_assignment/final_assignment.tsv
#
# If present, Step 4 calls are merged into the Step 5 query-prediction table.
#
# =============================================================================
# Outputs
# =============================================================================
#
# Written to:
#
#   results/06_rf_corroboration/
#
# Main outputs:
#
#   step5_rf_panels_index.tsv / .rds
#   RF_all_panels_predictions_queries.tsv / .rds
#   RF_all_panels_cv_summary.tsv / .rds
#   RF_all_panels_cv_perclass.tsv / .rds
#   step5_random_forest_summary.xlsx
#   step5_run_info.rds
#
# Per-panel outputs:
#
#   RF_<panel>_predictions_queries.tsv
#   RF_<panel>_cv_summary.tsv
#   RF_<panel>_cv_perclass.tsv
#   RF_<panel>_cv_rows.tsv
#   RF_<panel>_variable_importance.tsv
#   FIG_RF_<panel>_validation_A4.pdf
#
# =============================================================================
# Run
# =============================================================================
#
#   Rscript steps/step5_random_forest_origin_tracing/run.R
#
# Optional:
#
#   Rscript steps/step5_random_forest_origin_tracing/run.R --cores 8 --trees 1000
#
# =============================================================================

suppressPackageStartupMessages({
  library(optparse)
  library(data.table)
  library(openxlsx)
})

# =============================================================================
# Repo-root detection
# =============================================================================

find_repo_root <- function(max_up = 10L) {
  wd <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
  cand <- wd
  
  for (i in seq_len(max_up + 1L)) {
    if (dir.exists(file.path(cand, "data")) && dir.exists(file.path(cand, "steps"))) {
      return(cand)
    }
    
    parent <- normalizePath(file.path(cand, ".."), winslash = "/", mustWork = FALSE)
    if (identical(parent, cand)) break
    cand <- parent
  }
  
  wd
}

repo_root <- find_repo_root()

is_abs_path <- function(p) {
  grepl("^(?:[A-Za-z]:[/\\\\]|/)", p)
}

resolve_path <- function(p, root = repo_root) {
  if (is.null(p) || !nzchar(p)) return(p)
  if (is_abs_path(p)) return(normalizePath(p, winslash = "/", mustWork = FALSE))
  normalizePath(file.path(root, p), winslash = "/", mustWork = FALSE)
}

# =============================================================================
# CLI
# =============================================================================

option_list <- list(
  make_option(
    "--qc_dir",
    type = "character",
    default = "results/01_qc",
    help = "Step 1-2 output directory containing metadata_clean.tsv [default %default]"
  ),
  make_option(
    "--step3_dir",
    type = "character",
    default = "results/02_snp_panels",
    help = "Step 3 output directory containing panels/ [default %default]"
  ),
  make_option(
    "--step4_dir",
    type = "character",
    default = "results/04_origin_assignment",
    help = "Step 4 output directory containing final_assignment.tsv, if available [default %default]"
  ),
  make_option(
    "--out_dir",
    type = "character",
    default = "results/06_rf_corroboration",
    help = "Step 5 output directory [default %default]"
  ),
  make_option(
    "--panels",
    type = "character",
    default = "P1_macroregion_africa_vs_asia,P2_subregion_within_africa,P3_subregion_within_asia",
    help = "Comma-separated Step 3 panel IDs to run [default %default]"
  ),
  make_option(
    "--query_is_reference_value",
    type = "character",
    default = "FALSE",
    help = "Metadata is_reference value identifying query/intercept samples [default %default]"
  ),
  
  # SNP/sample filters
  make_option(
    "--keep_snps_frac",
    type = "double",
    default = 0.70,
    help = "Keep SNPs with at least this non-missing fraction across panel samples [default %default]"
  ),
  make_option(
    "--min_snps_ref",
    type = "integer",
    default = 500,
    help = "Drop reference samples with fewer than this many non-missing SNPs [default %default]"
  ),
  make_option(
    "--min_snps_query",
    type = "integer",
    default = 200,
    help = "Flag query samples with fewer than this many non-missing SNPs as uncertain [default %default]"
  ),
  make_option(
    "--min_class_n",
    type = "integer",
    default = 5,
    help = "Drop reference classes with fewer than this many samples [default %default]"
  ),
  
  # Random Forest settings
  make_option(
    "--trees",
    type = "integer",
    default = 1000,
    help = "Number of trees [default %default]"
  ),
  make_option(
    "--mtry",
    type = "integer",
    default = 0,
    help = "mtry; 0 = sqrt(number of retained SNPs) [default %default]"
  ),
  make_option(
    "--min_node_size",
    type = "integer",
    default = 1,
    help = "Minimum node size for ranger [default %default]"
  ),
  make_option(
    "--seed",
    type = "integer",
    default = 1,
    help = "Random seed [default %default]"
  ),
  make_option(
    "--cores",
    type = "integer",
    default = 0,
    help = "Threads for ranger. 0 = all detected cores minus one [default %default]"
  ),
  
  # Cross-validation
  make_option(
    "--folds",
    type = "integer",
    default = 5,
    help = "Number of stratified CV folds [default %default]"
  ),
  make_option(
    "--reps",
    type = "integer",
    default = 5,
    help = "Number of repeated CV rounds [default %default]"
  ),
  make_option(
    "--write_cv_rows",
    type = "character",
    default = "TRUE",
    help = "Write per-sample CV rows: TRUE/FALSE [default %default]"
  ),
  
  # RF confidence thresholds
  make_option(
    "--high_prob",
    type = "double",
    default = 0.95,
    help = "High-confidence RF threshold [default %default]"
  ),
  make_option(
    "--moderate_prob",
    type = "double",
    default = 0.85,
    help = "Moderate-confidence RF threshold [default %default]"
  ),
  make_option(
    "--min_gap",
    type = "double",
    default = 0.20,
    help = "Flag uncertain if top probability minus second probability is below this [default %default]"
  )
)

opt <- parse_args(OptionParser(option_list = option_list))

opt$qc_dir <- resolve_path(opt$qc_dir)
opt$step3_dir <- resolve_path(opt$step3_dir)
opt$step4_dir <- resolve_path(opt$step4_dir)
opt$out_dir <- resolve_path(opt$out_dir)

if (opt$cores <= 0) {
  opt$cores <- max(1L, parallel::detectCores(logical = TRUE) - 1L)
}

dir.create(opt$out_dir, recursive = TRUE, showWarnings = FALSE)

panels <- trimws(unlist(strsplit(opt$panels, ",")))
panels <- panels[nzchar(panels)]

message("Repo root:  ", repo_root)
message("QC dir:     ", opt$qc_dir)
message("Step 3 dir: ", opt$step3_dir)
message("Step 4 dir: ", opt$step4_dir)
message("Output dir: ", opt$out_dir)
message("Panels:     ", paste(panels, collapse = ", "))
message("Cores:      ", opt$cores)

# =============================================================================
# Helpers
# =============================================================================

clean_text <- function(x) {
  x <- as.character(x)
  x <- gsub("\u00A0", " ", x, fixed = TRUE)
  x <- gsub("[\u200B-\u200D\uFEFF]", "", x)
  x <- trimws(x)
  x[x %in% c("", "NA", "NaN", "NULL", "null")] <- NA_character_
  x
}

parse_bool1 <- function(x, default = FALSE, argname = "") {
  if (is.null(x) || length(x) == 0L) return(as.logical(default)[1])
  
  y <- tolower(clean_text(x[1]))
  
  if (is.na(y) || !nzchar(y)) return(as.logical(default)[1])
  if (y %in% c("true", "t", "1", "yes", "y")) return(TRUE)
  if (y %in% c("false", "f", "0", "no", "n")) return(FALSE)
  
  stop("Cannot parse boolean for ", argname, ": ", x)
}

as_clean_logical <- function(x) {
  if (is.logical(x)) return(x)
  
  y <- tolower(clean_text(x))
  
  out <- rep(NA, length(y))
  out[y %in% c("true", "t", "1", "yes", "y", "reference", "ref")] <- TRUE
  out[y %in% c("false", "f", "0", "no", "n", "query", "intercept")] <- FALSE
  
  out
}

panel_to_groupcol <- function(panel_id) {
  if (grepl("^P1_", panel_id)) return("macroregion_3")
  if (grepl("^P2_", panel_id)) return("subregion")
  if (grepl("^P3_", panel_id)) return("subregion")
  if (grepl("^P4_", panel_id)) return("population")
  if (grepl("macroregion", panel_id, ignore.case = TRUE)) return("macroregion_3")
  if (grepl("subregion", panel_id, ignore.case = TRUE)) return("subregion")
  if (grepl("population", panel_id, ignore.case = TRUE)) return("population")
  "macroregion_3"
}

panel_reference_filter <- function(meta_ref, panel_id) {
  if (grepl("^P1_", panel_id)) {
    return(meta_ref[macroregion_3 %in% c("Africa", "Asia")])
  }
  
  if (grepl("^P2_", panel_id)) {
    return(meta_ref[macroregion_3 == "Africa"])
  }
  
  if (grepl("^P3_", panel_id)) {
    return(meta_ref[macroregion_3 == "Asia"])
  }
  
  meta_ref
}

second_best <- function(v) {
  v2 <- sort(v, decreasing = TRUE)
  if (length(v2) >= 2L) unname(v2[2]) else NA_real_
}

top_name <- function(v) {
  if (length(v) == 0L || all(is.na(v))) return(NA_character_)
  names(which.max(v))[1]
}

conf_label <- function(pmax, gap, n_snps, high, moderate, min_gap, min_snps_query) {
  if (is.na(pmax)) return("Uncertain")
  if (!is.na(n_snps) && n_snps < min_snps_query) return("Uncertain")
  if (!is.na(gap) && gap < min_gap) return("Uncertain")
  if (pmax >= high) return("High")
  if (pmax >= moderate) return("Moderate")
  "Low"
}

make_stratified_folds <- function(y, k = 5, seed = 1) {
  set.seed(seed)
  
  y <- as.factor(y)
  folds <- integer(length(y))
  idx <- seq_along(y)
  
  for (lev in levels(y)) {
    ii <- idx[y == lev]
    ii <- sample(ii, length(ii))
    folds[ii] <- rep(seq_len(k), length.out = length(ii))
  }
  
  folds
}

impute_by_train_means <- function(X_train, X_test = NULL) {
  mu <- colMeans(X_train, na.rm = TRUE)
  mu[is.na(mu)] <- 0.5
  
  X_train2 <- X_train
  
  for (j in seq_len(ncol(X_train2))) {
    miss <- is.na(X_train2[, j])
    if (any(miss)) X_train2[miss, j] <- mu[j]
  }
  
  if (is.null(X_test)) {
    return(list(X_train = X_train2, mu = mu))
  }
  
  X_test2 <- X_test
  
  for (j in seq_len(ncol(X_test2))) {
    miss <- is.na(X_test2[, j])
    if (any(miss)) X_test2[miss, j] <- mu[j]
  }
  
  list(X_train = X_train2, X_test = X_test2, mu = mu)
}

safe_sheet <- function(wb, name) {
  nm <- gsub("[\\[\\]\\*\\?/\\\\:]", "_", name)
  if (nchar(nm) > 31) nm <- substr(nm, 1, 31)
  
  existing <- names(wb)
  if (!(nm %in% existing)) return(nm)
  
  i <- 2
  repeat {
    suffix <- paste0("_", i)
    base <- substr(nm, 1, max(1, 31 - nchar(suffix)))
    nm2 <- paste0(base, suffix)
    if (!(nm2 %in% existing)) return(nm2)
    i <- i + 1
  }
}

safe_pdf <- function(path, width = 8.27, height = 11.69) {
  if ("cairo_pdf" %in% getNamespaceExports("grDevices")) {
    grDevices::cairo_pdf(path, width = width, height = height)
  } else {
    grDevices::pdf(path, width = width, height = height)
  }
}

# =============================================================================
# Random Forest engine
# =============================================================================

have_ranger <- requireNamespace("ranger", quietly = TRUE)
have_rf <- requireNamespace("randomForest", quietly = TRUE)

if (!have_ranger && !have_rf) {
  stop(
    "Step 5 requires either 'ranger' or 'randomForest'.\n",
    "Install one of them, preferably:\n",
    "install.packages('ranger')"
  )
}

fit_rf <- function(X_train, y_train, mtry, trees, min_node_size, seed, cores) {
  y_train <- as.factor(y_train)
  
  if (mtry <= 0) {
    mtry <- max(1L, floor(sqrt(ncol(X_train))))
  }
  
  if (have_ranger) {
    set.seed(seed)
    
    fit <- ranger::ranger(
      x = as.data.frame(X_train),
      y = y_train,
      num.trees = trees,
      mtry = mtry,
      min.node.size = min_node_size,
      probability = TRUE,
      importance = "impurity",
      seed = seed,
      num.threads = cores
    )
    
    return(list(engine = "ranger", fit = fit, levels = levels(y_train)))
  }
  
  set.seed(seed)
  
  fit <- randomForest::randomForest(
    x = X_train,
    y = y_train,
    ntree = trees,
    mtry = mtry,
    importance = TRUE
  )
  
  list(engine = "randomForest", fit = fit, levels = levels(y_train))
}

predict_rf_prob <- function(model, X_test) {
  if (nrow(X_test) == 0L) {
    return(matrix(numeric(0), nrow = 0, ncol = length(model$levels)))
  }
  
  if (model$engine == "ranger") {
    p <- predict(model$fit, data = as.data.frame(X_test))$predictions
  } else {
    p <- predict(model$fit, newdata = X_test, type = "prob")
  }
  
  p <- as.matrix(p)
  
  missing_cols <- setdiff(model$levels, colnames(p))
  
  if (length(missing_cols) > 0L) {
    add <- matrix(
      0,
      nrow = nrow(p),
      ncol = length(missing_cols),
      dimnames = list(rownames(p), missing_cols)
    )
    p <- cbind(p, add)
  }
  
  p <- p[, model$levels, drop = FALSE]
  p
}

get_importance <- function(model) {
  if (model$engine == "ranger") {
    imp <- model$fit$variable.importance
  } else {
    imp <- randomForest::importance(model$fit)
    if (is.matrix(imp)) {
      if ("MeanDecreaseGini" %in% colnames(imp)) {
        imp <- imp[, "MeanDecreaseGini"]
      } else {
        imp <- imp[, 1]
      }
    }
  }
  
  data.table(
    snp_id = names(imp),
    importance = as.numeric(imp)
  )[order(-importance)]
}

summarise_prob_matrix <- function(prob, sample_ids, n_snps_used, high, moderate, min_gap, min_snps_query) {
  if (nrow(prob) == 0L) {
    return(data.table())
  }
  
  rows <- vector("list", nrow(prob))
  
  for (i in seq_len(nrow(prob))) {
    v <- prob[i, ]
    tg <- top_name(v)
    tp <- if (!is.na(tg)) unname(v[tg]) else NA_real_
    sp <- second_best(v)
    sg <- if (length(v) >= 2L) names(sort(v, decreasing = TRUE))[2] else NA_character_
    gap <- if (!is.na(tp) && !is.na(sp)) tp - sp else NA_real_
    
    rows[[i]] <- data.table(
      sample_id = sample_ids[i],
      top_group = tg,
      top_prob = tp,
      second_group = sg,
      second_prob = sp,
      prob_gap = gap,
      n_snps_used = n_snps_used[i],
      confidence = conf_label(
        pmax = tp,
        gap = gap,
        n_snps = n_snps_used[i],
        high = high,
        moderate = moderate,
        min_gap = min_gap,
        min_snps_query = min_snps_query
      )
    )
  }
  
  rbindlist(rows, fill = TRUE)
}

# =============================================================================
# Load metadata and optional Step 4 calls
# =============================================================================

write_cv_rows <- parse_bool1(
  opt$write_cv_rows,
  default = TRUE,
  argname = "--write_cv_rows"
)

meta_path <- file.path(opt$qc_dir, "metadata_clean.tsv")

if (!file.exists(meta_path)) {
  stop("Missing metadata_clean.tsv: ", meta_path)
}

meta <- fread(meta_path)
setnames(meta, tolower(names(meta)))

need_cols <- c("sample_id", "is_reference", "macroregion_3", "subregion", "population")
missing_cols <- setdiff(need_cols, names(meta))

if (length(missing_cols) > 0L) {
  stop("metadata_clean.tsv missing column(s): ", paste(missing_cols, collapse = ", "))
}

for (nm in names(meta)) {
  if (!inherits(meta[[nm]], c("numeric", "integer", "logical", "Date", "POSIXct"))) {
    meta[[nm]] <- clean_text(meta[[nm]])
  }
}

meta[, sample_id := clean_text(sample_id)]
meta[, is_reference := as_clean_logical(is_reference)]
meta[, macroregion_3 := clean_text(macroregion_3)]
meta[, subregion := clean_text(subregion)]
meta[, population := clean_text(population)]

if ("country" %in% names(meta)) {
  meta[, country := clean_text(country)]
}

query_is_ref <- parse_bool1(
  opt$query_is_reference_value,
  default = FALSE,
  argname = "--query_is_reference_value"
)

query_ids_all <- meta[is_reference == query_is_ref, sample_id]
ref_ids_all <- meta[is_reference %in% TRUE, sample_id]

if (length(query_ids_all) == 0L) {
  stop("No query samples found with is_reference == ", query_is_ref)
}

if (length(ref_ids_all) == 0L) {
  stop("No reference samples found with is_reference == TRUE")
}

step4_file <- file.path(opt$step4_dir, "final_assignment.tsv")

if (file.exists(step4_file)) {
  step4_final <- fread(step4_file)
  setnames(step4_final, tolower(names(step4_final)))
  
  step4_keep <- intersect(
    c(
      "sample_id",
      "macroregion_call",
      "macroregion_confidence",
      "macroregion_reason",
      "macroregion_agreement",
      "macroregion_tail_agreement",
      "subregion_call",
      "subregion_confidence",
      "subregion_reason",
      "subregion_panel",
      "subregion_agreement",
      "subregion_tail_agreement"
    ),
    names(step4_final)
  )
  
  step4_final <- step4_final[, ..step4_keep]
  
  message("Loaded Step 4 final assignment: ", step4_file)
} else {
  step4_final <- data.table(sample_id = character())
  message("No Step 4 final_assignment.tsv found. Step 5 will run without Step 4 comparison.")
}

# =============================================================================
# Run one panel
# =============================================================================

run_panel_rf <- function(panel_id) {
  message("\n============================================================")
  message("Running RF panel: ", panel_id)
  message("============================================================")
  
  panel_dir <- file.path(opt$step3_dir, "panels", panel_id)
  snp_matrix_path <- file.path(panel_dir, "snp_matrix.rds")
  snp_map_path <- file.path(panel_dir, "snp_map.tsv")
  
  if (!file.exists(snp_matrix_path)) {
    warning("Skipping panel; missing: ", snp_matrix_path)
    return(NULL)
  }
  
  if (!file.exists(snp_map_path)) {
    warning("Skipping panel; missing: ", snp_map_path)
    return(NULL)
  }
  
  group_col <- panel_to_groupcol(panel_id)
  
  X0 <- readRDS(snp_matrix_path)
  
  if (!is.matrix(X0)) {
    X0 <- as.matrix(X0)
  }
  
  storage.mode(X0) <- "integer"
  
  if (is.null(rownames(X0)) || is.null(colnames(X0))) {
    stop("SNP matrix for ", panel_id, " lacks rownames or colnames")
  }
  
  meta_ref <- meta[is_reference %in% TRUE]
  meta_ref <- panel_reference_filter(meta_ref, panel_id)
  meta_ref <- meta_ref[!is.na(get(group_col)) & clean_text(get(group_col)) != ""]
  
  ref_ids <- intersect(meta_ref$sample_id, colnames(X0))
  query_ids <- intersect(query_ids_all, colnames(X0))
  
  if (length(ref_ids) == 0L) {
    warning("Skipping ", panel_id, ": no reference samples in matrix")
    return(NULL)
  }
  
  if (length(query_ids) == 0L) {
    warning("Panel ", panel_id, ": no query samples in matrix; validation still runs")
  }
  
  all_panel_ids <- unique(c(ref_ids, query_ids))
  
  keep_snp <- rowMeans(!is.na(X0[, all_panel_ids, drop = FALSE])) >= opt$keep_snps_frac
  X0 <- X0[keep_snp, , drop = FALSE]
  
  if (nrow(X0) == 0L) {
    warning("Skipping ", panel_id, ": no SNPs left after missingness filter")
    return(NULL)
  }
  
  ref_nonmiss <- colSums(!is.na(X0[, ref_ids, drop = FALSE]))
  ref_ids <- ref_ids[ref_nonmiss[ref_ids] >= opt$min_snps_ref]
  
  if (length(ref_ids) == 0L) {
    warning("Skipping ", panel_id, ": no reference samples pass min_snps_ref")
    return(NULL)
  }
  
  meta_ref2 <- meta_ref[sample_id %in% ref_ids]
  class_counts <- meta_ref2[, .N, by = group_col]
  setnames(class_counts, group_col, "class")
  
  keep_classes <- class_counts[N >= opt$min_class_n, class]
  
  meta_ref2 <- meta_ref2[get(group_col) %in% keep_classes]
  ref_ids <- meta_ref2$sample_id
  
  class_counts_final <- meta_ref2[, .N, by = group_col]
  setnames(class_counts_final, group_col, "class")
  
  if (nrow(class_counts_final) < 2L) {
    warning("Skipping ", panel_id, ": fewer than two classes after min_class_n")
    return(NULL)
  }
  
  y_ref <- as.factor(meta_ref2[[group_col]])
  names(y_ref) <- meta_ref2$sample_id
  
  X_ref <- t(X0[, ref_ids, drop = FALSE])
  X_query <- t(X0[, query_ids, drop = FALSE])
  
  n_snps_ref <- rowSums(!is.na(X_ref))
  n_snps_query <- if (length(query_ids) > 0L) rowSums(!is.na(X_query)) else integer(0)
  
  mtry <- opt$mtry
  if (mtry <= 0) {
    mtry <- max(1L, floor(sqrt(ncol(X_ref))))
  }
  
  message("Target:             ", group_col)
  message("Reference samples:  ", nrow(X_ref))
  message("Query samples:      ", nrow(X_query))
  message("SNPs retained:      ", ncol(X_ref))
  message("Classes:            ", paste(class_counts_final$class, class_counts_final$N, sep = "=", collapse = ", "))
  message("RF engine:          ", ifelse(have_ranger, "ranger", "randomForest"))
  
  # ---------------------------------------------------------------------------
  # Repeated stratified k-fold CV
  # ---------------------------------------------------------------------------
  
  cv_rows <- list()
  cv_i <- 1L
  
  min_class <- min(table(y_ref))
  k_eff <- min(opt$folds, min_class)
  
  if (k_eff < 2L) {
    warning("Panel ", panel_id, ": too few samples per class for CV")
    cv_dt <- data.table()
  } else {
    for (rep_i in seq_len(opt$reps)) {
      folds <- make_stratified_folds(y_ref, k = k_eff, seed = opt$seed + rep_i)
      
      for (fold_i in seq_len(k_eff)) {
        test_idx <- which(folds == fold_i)
        train_idx <- setdiff(seq_along(y_ref), test_idx)
        
        X_train <- X_ref[train_idx, , drop = FALSE]
        X_test <- X_ref[test_idx, , drop = FALSE]
        
        y_train <- y_ref[train_idx]
        y_test <- y_ref[test_idx]
        
        imp <- impute_by_train_means(X_train, X_test)
        
        model <- fit_rf(
          X_train = imp$X_train,
          y_train = y_train,
          mtry = mtry,
          trees = opt$trees,
          min_node_size = opt$min_node_size,
          seed = opt$seed + rep_i * 1000 + fold_i,
          cores = opt$cores
        )
        
        prob <- predict_rf_prob(model, imp$X_test)
        
        pred_dt <- summarise_prob_matrix(
          prob = prob,
          sample_ids = names(y_test),
          n_snps_used = rowSums(!is.na(X_test)),
          high = opt$high_prob,
          moderate = opt$moderate_prob,
          min_gap = opt$min_gap,
          min_snps_query = 0
        )
        
        pred_dt[, `:=`(
          panel_id = panel_id,
          group_col = group_col,
          rep = rep_i,
          fold = fold_i,
          true_group = as.character(y_test),
          correct = top_group == as.character(y_test)
        )]
        
        cv_rows[[cv_i]] <- pred_dt
        cv_i <- cv_i + 1L
      }
    }
    
    cv_dt <- rbindlist(cv_rows, fill = TRUE)
  }
  
  if (nrow(cv_dt) > 0L) {
    cv_summary <- cv_dt[
      ,
      .(
        n = .N,
        accuracy = mean(correct, na.rm = TRUE),
        mean_top_prob = mean(top_prob, na.rm = TRUE),
        median_top_prob = median(top_prob, na.rm = TRUE),
        mean_gap = mean(prob_gap, na.rm = TRUE),
        high_or_moderate_frac = mean(confidence %in% c("High", "Moderate"), na.rm = TRUE)
      ),
      by = .(panel_id, group_col)
    ]
    
    cv_perclass <- cv_dt[
      ,
      .(
        n = .N,
        accuracy = mean(correct, na.rm = TRUE),
        mean_top_prob = mean(top_prob, na.rm = TRUE),
        high_or_moderate_frac = mean(confidence %in% c("High", "Moderate"), na.rm = TRUE)
      ),
      by = .(panel_id, true_group)
    ][order(true_group)]
    
  } else {
    cv_summary <- data.table(
      panel_id = panel_id,
      group_col = group_col,
      n = 0L,
      accuracy = NA_real_,
      mean_top_prob = NA_real_,
      median_top_prob = NA_real_,
      mean_gap = NA_real_,
      high_or_moderate_frac = NA_real_
    )
    
    cv_perclass <- data.table()
  }
  
  # ---------------------------------------------------------------------------
  # Train final model and predict queries
  # ---------------------------------------------------------------------------
  
  imp_final <- impute_by_train_means(X_ref)
  
  final_model <- fit_rf(
    X_train = imp_final$X_train,
    y_train = y_ref,
    mtry = mtry,
    trees = opt$trees,
    min_node_size = opt$min_node_size,
    seed = opt$seed,
    cores = opt$cores
  )
  
  var_imp <- get_importance(final_model)
  
  if (length(query_ids) > 0L) {
    imp_query <- impute_by_train_means(X_ref, X_query)
    prob_query <- predict_rf_prob(final_model, imp_query$X_test)
    
    pred_query <- summarise_prob_matrix(
      prob = prob_query,
      sample_ids = query_ids,
      n_snps_used = n_snps_query[query_ids],
      high = opt$high_prob,
      moderate = opt$moderate_prob,
      min_gap = opt$min_gap,
      min_snps_query = opt$min_snps_query
    )
    
    pred_query[, `:=`(
      panel_id = panel_id,
      group_col = group_col,
      status = fifelse(n_snps_used < opt$min_snps_query, "too_few_snps", "ok")
    )]
    
    meta_cols <- intersect(
      c("sample_id", "country", "population", "macroregion_3", "subregion", "is_reference"),
      names(meta)
    )
    
    pred_query <- merge(
      pred_query,
      meta[, ..meta_cols],
      by = "sample_id",
      all.x = TRUE,
      sort = FALSE
    )
    
    if (nrow(step4_final) > 0L) {
      pred_query <- merge(
        pred_query,
        step4_final,
        by = "sample_id",
        all.x = TRUE,
        sort = FALSE
      )
      
      pred_query[, rf_vs_step4 := NA_character_]
      
      if (grepl("^P1_", panel_id)) {
        pred_query[
          !is.na(macroregion_call) & !is.na(top_group),
          rf_vs_step4 := fifelse(
            top_group == macroregion_call,
            "supports_step4_macroregion",
            "discordant_with_step4_macroregion"
          )
        ]
        
        pred_query[
          is.na(macroregion_call) | macroregion_confidence == "Uncertain",
          rf_vs_step4 := "step4_macroregion_uncertain"
        ]
      }
      
      if (grepl("^P2_", panel_id)) {
        pred_query[
          !is.na(subregion_call) & !is.na(top_group),
          rf_vs_step4 := fifelse(
            top_group == subregion_call,
            "supports_step4_subregion",
            "discordant_with_step4_subregion"
          )
        ]
        
        pred_query[
          !is.na(macroregion_call) & macroregion_call != "Africa",
          rf_vs_step4 := "not_interpreted_step4_not_africa"
        ]
        
        pred_query[
          is.na(subregion_call) | subregion_confidence == "Uncertain",
          rf_vs_step4 := fifelse(
            rf_vs_step4 %in% c("not_interpreted_step4_not_africa"),
            rf_vs_step4,
            "step4_subregion_uncertain"
          )
        ]
      }
      
      if (grepl("^P3_", panel_id)) {
        pred_query[
          !is.na(subregion_call) & !is.na(top_group),
          rf_vs_step4 := fifelse(
            top_group == subregion_call,
            "supports_step4_subregion",
            "discordant_with_step4_subregion"
          )
        ]
        
        pred_query[
          !is.na(macroregion_call) & macroregion_call != "Asia",
          rf_vs_step4 := "not_interpreted_step4_not_asia"
        ]
        
        pred_query[
          is.na(subregion_call) | subregion_confidence == "Uncertain",
          rf_vs_step4 := fifelse(
            rf_vs_step4 %in% c("not_interpreted_step4_not_asia"),
            rf_vs_step4,
            "step4_subregion_uncertain"
          )
        ]
      }
    }
    
  } else {
    pred_query <- data.table()
  }
  
  # ---------------------------------------------------------------------------
  # Write panel outputs
  # ---------------------------------------------------------------------------
  
  safe_panel <- gsub("[^A-Za-z0-9_]+", "_", panel_id)
  
  pred_file <- file.path(opt$out_dir, paste0("RF_", safe_panel, "_predictions_queries.tsv"))
  cv_sum_file <- file.path(opt$out_dir, paste0("RF_", safe_panel, "_cv_summary.tsv"))
  cv_pc_file <- file.path(opt$out_dir, paste0("RF_", safe_panel, "_cv_perclass.tsv"))
  cv_rows_file <- file.path(opt$out_dir, paste0("RF_", safe_panel, "_cv_rows.tsv"))
  imp_file <- file.path(opt$out_dir, paste0("RF_", safe_panel, "_variable_importance.tsv"))
  fig_file <- file.path(opt$out_dir, paste0("FIG_RF_", safe_panel, "_validation_A4.pdf"))
  
  fwrite(pred_query, pred_file, sep = "\t")
  fwrite(cv_summary, cv_sum_file, sep = "\t")
  fwrite(cv_perclass, cv_pc_file, sep = "\t")
  fwrite(var_imp, imp_file, sep = "\t")
  
  if (isTRUE(write_cv_rows)) {
    fwrite(cv_dt, cv_rows_file, sep = "\t")
  }
  
  # ---------------------------------------------------------------------------
  # Simple A4 validation figure
  # ---------------------------------------------------------------------------
  
  safe_pdf(fig_file)
  
  oldpar <- par(no.readonly = TRUE)
  on.exit(par(oldpar), add = TRUE)
  
  par(mfrow = c(3, 1), mar = c(5, 5, 4, 2))
  
  if (nrow(cv_perclass) > 0L) {
    barplot(
      cv_perclass$accuracy,
      names.arg = cv_perclass$true_group,
      las = 2,
      ylim = c(0, 1),
      main = paste0(panel_id, "\nCV accuracy by class"),
      ylab = "Accuracy"
    )
    abline(h = cv_summary$accuracy[1], lty = 2)
  } else {
    plot.new()
    title("No CV per-class results")
  }
  
  if (nrow(cv_dt) > 0L) {
    boxplot(
      top_prob ~ true_group,
      data = cv_dt,
      las = 2,
      ylim = c(0, 1),
      main = "CV top probability by true class",
      ylab = "Top RF probability"
    )
  } else {
    plot.new()
    title("No CV probability results")
  }
  
  if (nrow(pred_query) > 0L) {
    barplot(
      table(pred_query$top_group),
      las = 2,
      main = "Query predicted classes",
      ylab = "Number of queries"
    )
  } else {
    plot.new()
    title("No query predictions")
  }
  
  dev.off()
  
  panel_index <- data.table(
    panel_id = panel_id,
    group_col = group_col,
    engine = ifelse(have_ranger, "ranger", "randomForest"),
    n_snps_retained = ncol(X_ref),
    n_reference_samples = nrow(X_ref),
    n_query_samples = nrow(X_query),
    n_classes = nrow(class_counts_final),
    classes = paste(class_counts_final$class, class_counts_final$N, sep = "=", collapse = ","),
    cv_accuracy = cv_summary$accuracy[1],
    cv_mean_top_prob = cv_summary$mean_top_prob[1],
    query_high = if (nrow(pred_query) > 0L) sum(pred_query$confidence == "High", na.rm = TRUE) else 0L,
    query_moderate = if (nrow(pred_query) > 0L) sum(pred_query$confidence == "Moderate", na.rm = TRUE) else 0L,
    query_low = if (nrow(pred_query) > 0L) sum(pred_query$confidence == "Low", na.rm = TRUE) else 0L,
    query_uncertain = if (nrow(pred_query) > 0L) sum(pred_query$confidence == "Uncertain", na.rm = TRUE) else 0L,
    predictions_file = pred_file,
    cv_summary_file = cv_sum_file,
    cv_perclass_file = cv_pc_file,
    cv_rows_file = if (isTRUE(write_cv_rows)) cv_rows_file else NA_character_,
    importance_file = imp_file,
    figure_file = fig_file
  )
  
  list(
    index = panel_index,
    pred = pred_query,
    cv_summary = cv_summary,
    cv_perclass = cv_perclass,
    cv_rows = cv_dt,
    importance = var_imp
  )
}

# =============================================================================
# Run panels
# =============================================================================

panel_results <- list()

for (p in panels) {
  res <- run_panel_rf(p)
  if (!is.null(res)) {
    panel_results[[p]] <- res
  }
}

if (length(panel_results) == 0L) {
  stop("No panels completed successfully.")
}

index_dt <- rbindlist(lapply(panel_results, `[[`, "index"), fill = TRUE)

fwrite(index_dt, file.path(opt$out_dir, "step5_rf_panels_index.tsv"), sep = "\t")
saveRDS(index_dt, file.path(opt$out_dir, "step5_rf_panels_index.rds"))

all_pred <- rbindlist(lapply(panel_results, `[[`, "pred"), fill = TRUE)
all_cv_summary <- rbindlist(lapply(panel_results, `[[`, "cv_summary"), fill = TRUE)
all_cv_perclass <- rbindlist(lapply(panel_results, `[[`, "cv_perclass"), fill = TRUE)

fwrite(all_pred, file.path(opt$out_dir, "RF_all_panels_predictions_queries.tsv"), sep = "\t")
fwrite(all_cv_summary, file.path(opt$out_dir, "RF_all_panels_cv_summary.tsv"), sep = "\t")
fwrite(all_cv_perclass, file.path(opt$out_dir, "RF_all_panels_cv_perclass.tsv"), sep = "\t")

saveRDS(all_pred, file.path(opt$out_dir, "RF_all_panels_predictions_queries.rds"))
saveRDS(all_cv_summary, file.path(opt$out_dir, "RF_all_panels_cv_summary.rds"))
saveRDS(all_cv_perclass, file.path(opt$out_dir, "RF_all_panels_cv_perclass.rds"))

# =============================================================================
# Excel summary workbook
# =============================================================================

wb <- createWorkbook()

sn <- safe_sheet(wb, "PANELS_INDEX")
addWorksheet(wb, sn)
writeDataTable(wb, sn, index_dt)

sn <- safe_sheet(wb, "ALL_QUERY_PREDICTIONS")
addWorksheet(wb, sn)
writeDataTable(wb, sn, all_pred)

sn <- safe_sheet(wb, "CV_SUMMARY")
addWorksheet(wb, sn)
writeDataTable(wb, sn, all_cv_summary)

sn <- safe_sheet(wb, "CV_PERCLASS")
addWorksheet(wb, sn)
writeDataTable(wb, sn, all_cv_perclass)

params <- data.table(
  parameter = names(opt),
  value = vapply(opt, function(x) paste(x, collapse = ","), character(1))
)

params <- rbind(
  params,
  data.table(parameter = "write_cv_rows_parsed", value = as.character(write_cv_rows)),
  fill = TRUE
)

sn <- safe_sheet(wb, "PARAMS")
addWorksheet(wb, sn)
writeDataTable(wb, sn, params)

xlsx_out <- file.path(opt$out_dir, "step5_random_forest_summary.xlsx")
saveWorkbook(wb, xlsx_out, overwrite = TRUE)

# =============================================================================
# Run info
# =============================================================================

run_info <- list(
  step = "step5_random_forest_origin_tracing",
  repo_root = repo_root,
  qc_dir = opt$qc_dir,
  step3_dir = opt$step3_dir,
  step4_dir = opt$step4_dir,
  out_dir = opt$out_dir,
  panels = panels,
  engine = ifelse(have_ranger, "ranger", "randomForest"),
  write_cv_rows = write_cv_rows,
  parameters = opt,
  panel_index = index_dt,
  timestamp = Sys.time(),
  session_info = sessionInfo()
)

saveRDS(run_info, file.path(opt$out_dir, "step5_run_info.rds"))

message("\nDone.")
message("RF panel index:   ", file.path(opt$out_dir, "step5_rf_panels_index.tsv"))
message("All predictions:  ", file.path(opt$out_dir, "RF_all_panels_predictions_queries.tsv"))
message("Excel workbook:   ", xlsx_out)
message("Step 5 outputs:   ", opt$out_dir)