#!/usr/bin/env Rscript

# =============================================================================
# PESTFLY — Step 4: Hierarchical SNP-based origin assignment
# =============================================================================
#
# Purpose
# -------
# Assign query/intercept samples using the diagnostic SNP panels generated by
# Step 3.
#
# Assignment hierarchy:
#
#   1. P1 macroregion assignment:
#        Africa vs Asia
#
#   2. Conditional subregion assignment:
#        if P1 == Africa with High/Moderate confidence -> P2 Africa subregions
#        if P1 == Asia   with High/Moderate confidence -> P3 Asia subregions
#
# P4 population-level assignment is not used in the default workflow.
#
# =============================================================================
# Conceptual model
# =============================================================================
#
# Step 3 ranks SNPs by informativeness for each panel. Step 4 tests whether each
# query assignment is stable across increasing Top-K SNP subsets.
#
# Here, K means:
#
#   "Use the top K ranked SNPs from the panel."
#
# It does NOT mean:
#
#   - number of populations;
#   - ADMIXTURE K;
#   - k-means clustering.
#
# Example K grid:
#
#   1, 2, 3, 4, 5, 10, 20, 50, 100, 200, 500,
#   1000, 2000, 5000, 10000, all available SNPs
#
# The small K values are kept in the raw output because they are diagnostically
# useful. They show whether assignments are already obvious from a few SNPs or
# whether the signal only becomes stable once more markers are included.
#
# However, small K values should not determine whether an assignment is reliable
# if they are below the minimum number of usable SNPs required for assignment.
#
# Therefore:
#
#   - all K values are written to the raw output;
#   - only usable K values enter stability calculations.
#
# A usable K value is one for which the query has at least:
#
#   - min_snps_query_macroregion non-missing SNPs for P1;
#   - min_snps_query_subregion   non-missing SNPs for P2/P3.
#
# By default:
#
#   P1 requires >= 200 usable SNPs
#   P2/P3 require >= 300 usable SNPs
#
# =============================================================================
# Improved reliability/stability logic
# =============================================================================
#
# A final call is accepted as High/Moderate only if all conditions are met:
#
#   1. the largest usable K gives enough posterior support;
#   2. the posterior gap between first and second class is large enough;
#   3. enough usable K values are available;
#   4. most usable K values agree with the final largest-K call;
#   5. the largest-K tail agrees with the final largest-K call.
#
# The key stability metrics are:
#
#   agreement_frac
#     proportion of all usable K values matching the final largest-K call.
#
#   tail_agreement_frac
#     proportion of the largest usable K values matching the final largest-K call.
#
# By default:
#
#   min_agreement      = 0.90
#   tail_fraction      = 0.50
#   min_tail_agreement = 1.00
#
# Meaning:
#
#   - at least 90% of usable K values must agree with the final call;
#   - the largest 50% of usable K values must agree completely with the final call.
#
# This allows noisy behaviour at very small K, while requiring convergence at
# larger SNP subsets.
#
# =============================================================================
# Main inputs
# =============================================================================
#
#   results/01_qc/metadata_clean.tsv
#   results/02_snp_panels/panels_index.tsv
#   results/02_snp_panels/panels/<panel_id>/snp_map.tsv
#   results/02_snp_panels/panels/<panel_id>/snp_matrix.rds
#
# =============================================================================
# Main outputs
# =============================================================================
#
#   results/04_origin_assignment/final_assignment.tsv
#   results/04_origin_assignment/final_assignment.rds
#   results/04_origin_assignment/step4_assignment_multilevel_macroregion_first.xlsx
#
#   results/04_origin_assignment/step4_K_grid_used.tsv
#   results/04_origin_assignment/step4_K_grid_used.rds
#
#   results/04_origin_assignment/P1_macroregion_raw.tsv / .rds
#   results/04_origin_assignment/P1_macroregion_stability.tsv / .rds
#   results/04_origin_assignment/P2_africa_subregion_raw.tsv / .rds
#   results/04_origin_assignment/P2_africa_subregion_stability.tsv / .rds
#   results/04_origin_assignment/P3_asia_subregion_raw.tsv / .rds
#   results/04_origin_assignment/P3_asia_subregion_stability.tsv / .rds
#
# =============================================================================
# Recommended run
# =============================================================================
#
#   Rscript steps/step4_multilevel_assignment/run.R
#
# Explicit extended-K run:
#
#   Rscript steps/step4_multilevel_assignment/run.R \
#     --extra_K 1000,2000,5000,10000 \
#     --include_all_snps_K TRUE \
#     --tail_fraction 0.50 \
#     --min_tail_agreement 1.00 \
#     --min_agreement 0.90
#
# =============================================================================

suppressPackageStartupMessages({
  library(optparse)
  library(data.table)
  library(openxlsx)
})

# =============================================================================
# Repo-root detection
# =============================================================================

find_repo_root <- function(max_up = 10L) {
  wd <- normalizePath(getwd(), winslash = "/", mustWork = TRUE)
  cand <- wd
  
  for (i in seq_len(max_up + 1L)) {
    if (dir.exists(file.path(cand, "data")) && dir.exists(file.path(cand, "steps"))) {
      return(cand)
    }
    
    parent <- normalizePath(file.path(cand, ".."), winslash = "/", mustWork = FALSE)
    if (identical(parent, cand)) break
    cand <- parent
  }
  
  wd
}

repo_root <- find_repo_root()

is_abs_path <- function(p) {
  grepl("^(?:[A-Za-z]:[/\\\\]|/)", p)
}

resolve_path <- function(p, root = repo_root) {
  if (is.null(p) || !nzchar(p)) return(p)
  if (is_abs_path(p)) return(normalizePath(p, winslash = "/", mustWork = FALSE))
  normalizePath(file.path(root, p), winslash = "/", mustWork = FALSE)
}

# =============================================================================
# CLI
# =============================================================================

option_list <- list(
  make_option(
    "--qc_dir",
    type = "character",
    default = "results/01_qc",
    help = "Step 1-2 output directory containing metadata_clean.tsv [default %default]"
  ),
  make_option(
    "--step3_dir",
    type = "character",
    default = "results/02_snp_panels",
    help = "Step 3 output directory containing panels_index.tsv and panels/ [default %default]"
  ),
  make_option(
    "--out_dir",
    type = "character",
    default = "results/04_origin_assignment",
    help = "Output directory [default %default]"
  ),
  make_option(
    "--out_xlsx",
    type = "character",
    default = "step4_assignment_multilevel_macroregion_first.xlsx",
    help = "Output Excel workbook filename [default %default]"
  ),
  make_option(
    "--query_is_reference_value",
    type = "character",
    default = "FALSE",
    help = "Metadata is_reference value identifying query/intercept samples [default %default]"
  ),
  
  # Minimum usable SNPs
  make_option(
    "--min_snps_query_macroregion",
    type = "integer",
    default = 200,
    help = "Minimum non-missing SNPs required for P1 macroregion assignment [default %default]"
  ),
  make_option(
    "--min_snps_query_subregion",
    type = "integer",
    default = 300,
    help = "Minimum non-missing SNPs required for P2/P3 subregion assignment [default %default]"
  ),
  
  # Likelihood model
  make_option(
    "--pseudocount",
    type = "double",
    default = 0.5,
    help = "Laplace smoothing pseudocount for reference allele frequencies [default %default]"
  ),
  make_option(
    "--epsilon",
    type = "double",
    default = 0.02,
    help = "Per-site genotype error/flip probability [default %default]"
  ),
  
  # Posterior thresholds
  make_option(
    "--high_posterior",
    type = "double",
    default = 0.95,
    help = "High posterior threshold [default %default]"
  ),
  make_option(
    "--moderate_posterior",
    type = "double",
    default = 0.85,
    help = "Moderate posterior lower bound [default %default]"
  ),
  make_option(
    "--min_gap_macroregion",
    type = "double",
    default = 0.20,
    help = "Minimum top-second posterior gap for P1 [default %default]"
  ),
  make_option(
    "--min_gap_subregion",
    type = "double",
    default = 0.25,
    help = "Minimum top-second posterior gap for P2/P3 [default %default]"
  ),
  
  # Multi-K grid
  make_option(
    "--base_K",
    type = "character",
    default = "1,2,3,4,5,10,20,50,100,200,500",
    help = "Comma-separated base K values [default %default]"
  ),
  make_option(
    "--extra_K",
    type = "character",
    default = "1000,2000,5000,10000",
    help = "Comma-separated extra K values tested when available [default %default]"
  ),
  make_option(
    "--auto_extend_K",
    type = "character",
    default = "TRUE",
    help = "Auto-extend K grid beyond base_K when enough SNPs are available: TRUE/FALSE [default %default]"
  ),
  make_option(
    "--include_all_snps_K",
    type = "character",
    default = "TRUE",
    help = "Include all available SNPs as final K value: TRUE/FALSE [default %default]"
  ),
  make_option(
    "--max_K_points",
    type = "integer",
    default = 30,
    help = "Maximum number of K points after auto-extension [default %default]"
  ),
  
  # Stability thresholds
  make_option(
    "--min_agreement",
    type = "double",
    default = 0.90,
    help = "Minimum fraction of usable K calls matching the final largest-K call [default %default]"
  ),
  make_option(
    "--min_K_available",
    type = "integer",
    default = 6,
    help = "Minimum number of usable K results needed to judge stability [default %default]"
  ),
  make_option(
    "--tail_fraction",
    type = "double",
    default = 0.50,
    help = "Fraction of largest usable K values used for tail-stability check [default %default]"
  ),
  make_option(
    "--min_tail_agreement",
    type = "double",
    default = 1.00,
    help = "Required agreement with final call among largest usable-K tail values [default %default]"
  )
)

opt <- parse_args(OptionParser(option_list = option_list))

opt$qc_dir <- resolve_path(opt$qc_dir)
opt$step3_dir <- resolve_path(opt$step3_dir)
opt$out_dir <- resolve_path(opt$out_dir)

dir.create(opt$out_dir, recursive = TRUE, showWarnings = FALSE)

message("Repo root:  ", repo_root)
message("QC dir:     ", opt$qc_dir)
message("Step 3 dir: ", opt$step3_dir)
message("Output dir: ", opt$out_dir)

# =============================================================================
# Helpers
# =============================================================================

clean_text <- function(x) {
  x <- as.character(x)
  x <- gsub("\u00A0", " ", x, fixed = TRUE)
  x <- gsub("[\u200B-\u200D\uFEFF]", "", x)
  x <- trimws(x)
  x[x %in% c("", "NA", "NaN", "NULL", "null")] <- NA_character_
  x
}

parse_bool1 <- function(x, default = FALSE, argname = "") {
  if (is.null(x) || length(x) == 0L) return(as.logical(default)[1])
  
  y <- tolower(clean_text(x[1]))
  
  if (is.na(y) || !nzchar(y)) return(as.logical(default)[1])
  if (y %in% c("true", "t", "1", "yes", "y")) return(TRUE)
  if (y %in% c("false", "f", "0", "no", "n")) return(FALSE)
  
  stop("Cannot parse boolean for ", argname, ": '", x, "'. Use TRUE/FALSE.")
}

parse_integer_vector <- function(x) {
  if (is.null(x) || length(x) == 0L || is.na(x) || !nzchar(x)) {
    return(integer())
  }
  
  out <- suppressWarnings(as.integer(clean_text(strsplit(x, ",")[[1]])))
  out <- out[!is.na(out) & out > 0L]
  sort(unique(out))
}

as_clean_logical <- function(x) {
  if (is.logical(x)) return(x)
  
  y <- tolower(clean_text(x))
  
  out <- rep(NA, length(y))
  out[y %in% c("true", "t", "1", "yes", "y", "reference", "ref")] <- TRUE
  out[y %in% c("false", "f", "0", "no", "n", "query", "intercept")] <- FALSE
  
  out
}

conf_label <- function(pmax, high = 0.95, mod = 0.85) {
  if (is.na(pmax)) return("NA")
  if (pmax >= high) return("High")
  if (pmax >= mod) return("Moderate")
  "Low"
}

safe_intersect <- function(x, y) {
  intersect(as.character(x), as.character(y))
}

loglik_one_group <- function(qvec, pvec, epsilon = 0.02) {
  ok <- !is.na(qvec) & !is.na(pvec)
  
  if (!any(ok)) return(NA_real_)
  
  q <- qvec[ok]
  p <- pvec[ok]
  
  p1 <- p * (1 - epsilon) + (1 - p) * epsilon
  p0 <- (1 - p) * (1 - epsilon) + p * epsilon
  
  p1 <- pmin(pmax(p1, 1e-12), 1 - 1e-12)
  p0 <- pmin(pmax(p0, 1e-12), 1 - 1e-12)
  
  sum(ifelse(q == 1, log(p1), log(p0)))
}

post_from_ll <- function(lls) {
  if (all(is.na(lls))) return(rep(NA_real_, length(lls)))
  
  m <- max(lls, na.rm = TRUE)
  w <- exp(lls - m)
  w[is.na(w)] <- 0
  
  if (sum(w) <= 0) return(rep(NA_real_, length(lls)))
  
  out <- w / sum(w)
  names(out) <- names(lls)
  out
}

make_Ks <- function(
    n_snps,
    baseK,
    extraK = c(1000L, 2000L, 5000L, 10000L),
    auto_extend = TRUE,
    include_all = TRUE,
    max_points = 30
) {
  if (is.na(n_snps) || n_snps <= 0L) {
    return(integer())
  }
  
  baseK <- sort(unique(as.integer(baseK)))
  baseK <- baseK[!is.na(baseK) & baseK > 0L]
  
  extraK <- sort(unique(as.integer(extraK)))
  extraK <- extraK[!is.na(extraK) & extraK > 0L]
  
  Ks <- baseK[baseK <= n_snps]
  
  if (isTRUE(auto_extend)) {
    Ks <- sort(unique(c(Ks, extraK[extraK <= n_snps])))
  }
  
  if (isTRUE(include_all)) {
    Ks <- sort(unique(c(Ks, as.integer(n_snps))))
  }
  
  Ks <- Ks[Ks <= n_snps]
  Ks <- sort(unique(Ks))
  
  if (length(Ks) > max_points) {
    small_K <- Ks[Ks <= 500L]
    large_K <- Ks[Ks > 500L]
    
    if (length(large_K) > 0L) {
      keep_large <- unique(round(seq(
        from = min(large_K),
        to = max(large_K),
        length.out = max(1L, max_points - length(small_K))
      )))
      
      Ks <- sort(unique(c(small_K, keep_large, max(Ks))))
    }
    
    if (length(Ks) > max_points) {
      Ks <- sort(unique(c(head(Ks, max_points - 1L), max(Ks))))
    }
  }
  
  Ks
}

stable_from_threshold <- function(dt, final_group) {
  dt2 <- dt[status %in% c("ok", "low_gap") & !is.na(top_group)]
  
  if (nrow(dt2) == 0L || is.na(final_group)) return(NA_real_)
  
  dt2 <- dt2[order(K)]
  Ks_sorted <- sort(unique(dt2$K))
  
  for (k in Ks_sorted) {
    later <- dt2[K >= k]
    if (nrow(later) > 0L && all(later$top_group == final_group)) {
      return(as.numeric(k))
    }
  }
  
  NA_real_
}

tail_agreement_with_final <- function(dt, final_group, tail_fraction = 0.50) {
  dt2 <- dt[status %in% c("ok", "low_gap") & !is.na(top_group)]
  
  if (nrow(dt2) == 0L || is.na(final_group)) {
    return(NA_real_)
  }
  
  dt2 <- dt2[order(K)]
  
  n_tail <- ceiling(nrow(dt2) * tail_fraction)
  n_tail <- max(1L, n_tail)
  
  tail_dt <- tail(dt2, n_tail)
  
  mean(tail_dt$top_group == final_group)
}

safe_sheet <- function(wb, name) {
  nm <- gsub("[\\[\\]\\*\\?/\\\\:]", "_", name)
  
  if (nchar(nm) > 31) {
    nm <- substr(nm, 1, 31)
  }
  
  existing <- names(wb)
  
  if (!(nm %in% existing)) return(nm)
  
  i <- 2
  
  repeat {
    suffix <- paste0("_", i)
    base <- substr(nm, 1, max(1, 31 - nchar(suffix)))
    nm2 <- paste0(base, suffix)
    
    if (!(nm2 %in% existing)) return(nm2)
    
    i <- i + 1
  }
}

# =============================================================================
# Core assignment functions
# =============================================================================

build_ref_freqs <- function(snp_mat, meta_ref, group_col, pseudocount = 0.5) {
  if (!(group_col %in% names(meta_ref))) {
    stop(
      "metadata missing group_col: ", group_col,
      "\nAvailable: ", paste(names(meta_ref), collapse = ", ")
    )
  }
  
  ref_ids <- safe_intersect(meta_ref$sample_id, colnames(snp_mat))
  
  if (length(ref_ids) < 4L) {
    return(list(freq = NULL, groups = character(0), ref_ids = ref_ids))
  }
  
  meta_ref2 <- meta_ref[sample_id %in% ref_ids]
  meta_ref2 <- meta_ref2[!is.na(get(group_col)) & clean_text(get(group_col)) != ""]
  
  if (nrow(meta_ref2) == 0L) {
    return(list(freq = NULL, groups = character(0), ref_ids = ref_ids))
  }
  
  groups <- sort(unique(meta_ref2[[group_col]]))
  groups <- groups[!is.na(groups) & clean_text(groups) != ""]
  
  if (length(groups) < 2L) {
    return(list(freq = NULL, groups = groups, ref_ids = ref_ids))
  }
  
  freq <- matrix(
    NA_real_,
    nrow = nrow(snp_mat),
    ncol = length(groups),
    dimnames = list(rownames(snp_mat), groups)
  )
  
  ids_by_group <- lapply(groups, function(g) {
    meta_ref2[get(group_col) == g, sample_id]
  })
  
  names(ids_by_group) <- groups
  
  for (g in groups) {
    ids <- safe_intersect(ids_by_group[[g]], colnames(snp_mat))
    
    if (length(ids) == 0L) next
    
    X <- snp_mat[, ids, drop = FALSE]
    
    alt_ct <- rowSums(X == 1, na.rm = TRUE)
    ref_ct <- rowSums(X == 0, na.rm = TRUE)
    tot_ct <- alt_ct + ref_ct
    
    p <- rep(NA_real_, length(tot_ct))
    ok <- tot_ct > 0
    
    p[ok] <- (alt_ct[ok] + pseudocount) / (tot_ct[ok] + 2 * pseudocount)
    
    freq[, g] <- p
  }
  
  list(freq = freq, groups = groups, ref_ids = ref_ids)
}

assign_panel_multiK <- function(
    panel_id,
    panel_dir,
    group_col,
    meta,
    query_ids,
    Ks,
    pseudocount,
    epsilon,
    min_snps_query,
    high_thr,
    mod_thr,
    min_gap,
    tail_fraction
) {
  snp_rds <- file.path(panel_dir, "snp_matrix.rds")
  snp_map_file <- file.path(panel_dir, "snp_map.tsv")
  
  if (!file.exists(snp_rds) || !file.exists(snp_map_file)) {
    stab <- data.table(
      panel_id = panel_id,
      sample_id = query_ids,
      status = "missing_panel_files"
    )
    return(list(raw = data.table(), stab = stab))
  }
  
  snp_mat_all <- readRDS(snp_rds)
  
  if (!is.matrix(snp_mat_all)) {
    snp_mat_all <- as.matrix(snp_mat_all)
  }
  
  storage.mode(snp_mat_all) <- "integer"
  
  if (is.null(rownames(snp_mat_all)) || is.null(colnames(snp_mat_all))) {
    stab <- data.table(
      panel_id = panel_id,
      sample_id = query_ids,
      status = "bad_snp_matrix_dimnames"
    )
    return(list(raw = data.table(), stab = stab))
  }
  
  sm <- fread(snp_map_file)
  
  if (!("snp_id" %in% names(sm))) {
    stop("snp_map.tsv missing snp_id in panel ", panel_id)
  }
  
  if ("score" %in% names(sm)) {
    sm <- sm[order(-score)]
  } else if ("best_fst" %in% names(sm)) {
    sm <- sm[order(-best_fst)]
  }
  
  sm <- sm[snp_id %in% rownames(snp_mat_all)]
  
  q_ids <- safe_intersect(query_ids, colnames(snp_mat_all))
  
  if (length(q_ids) == 0L) {
    stab <- data.table(
      panel_id = panel_id,
      sample_id = query_ids,
      status = "no_queries_in_panel_matrix"
    )
    return(list(raw = data.table(), stab = stab))
  }
  
  if (nrow(sm) == 0L) {
    stab <- data.table(
      panel_id = panel_id,
      sample_id = q_ids,
      status = "no_snps_in_map_or_matrix"
    )
    return(list(raw = data.table(), stab = stab))
  }
  
  meta_ref <- meta[is_reference %in% TRUE]
  
  # Publication-safe hierarchical reference filtering.
  # P1 is trained only on Africa/Asia macroregion references.
  # P2 is trained only on African references.
  # P3 is trained only on Asian references.
  if (panel_id == "P1_macroregion_africa_vs_asia") {
    meta_ref <- meta_ref[macroregion_3 %in% c("Africa", "Asia")]
  }
  
  if (panel_id == "P2_subregion_within_africa") {
    meta_ref <- meta_ref[macroregion_3 == "Africa"]
  }
  
  if (panel_id == "P3_subregion_within_asia") {
    meta_ref <- meta_ref[macroregion_3 == "Asia"]
  }
  
  rf_full <- build_ref_freqs(
    snp_mat = snp_mat_all,
    meta_ref = meta_ref,
    group_col = group_col,
    pseudocount = pseudocount
  )
  
  if (is.null(rf_full$freq) || length(rf_full$groups) < 2L) {
    stab <- data.table(
      panel_id = panel_id,
      sample_id = q_ids,
      status = "no_groups_or_freqs"
    )
    return(list(raw = data.table(), stab = stab))
  }
  
  Ks <- Ks[Ks <= nrow(sm)]
  Ks <- sort(unique(Ks))
  
  if (length(Ks) == 0L) {
    stab <- data.table(
      panel_id = panel_id,
      sample_id = q_ids,
      status = "no_K_available"
    )
    return(list(raw = data.table(), stab = stab))
  }
  
  raw_list <- vector("list", length(Ks) * length(q_ids))
  z <- 1L
  
  for (K in Ks) {
    snp_ids_K <- sm$snp_id[seq_len(min(K, nrow(sm)))]
    
    X <- snp_mat_all[snp_ids_K, , drop = FALSE]
    rf <- rf_full$freq[snp_ids_K, , drop = FALSE]
    
    ok_anyp <- rowSums(!is.na(rf)) > 0
    
    for (sid in q_ids) {
      qvec <- X[, sid]
      n_used <- sum(!is.na(qvec) & ok_anyp)
      
      if (is.na(n_used) || n_used < min_snps_query) {
        raw_list[[z]] <- data.table(
          panel_id = panel_id,
          group_col = group_col,
          K = as.integer(K),
          sample_id = sid,
          top_group = NA_character_,
          top_posterior = NA_real_,
          second_group = NA_character_,
          second_posterior = NA_real_,
          posterior_gap = NA_real_,
          n_snps_used = as.integer(n_used),
          confidence = "Low",
          status = "too_few_snps",
          note = paste0("Need >= ", min_snps_query, "; have ", n_used)
        )
        
        z <- z + 1L
        next
      }
      
      lls <- vapply(
        rf_full$groups,
        function(g) loglik_one_group(qvec, rf[, g], epsilon = epsilon),
        numeric(1)
      )
      
      post <- post_from_ll(lls)
      
      if (all(is.na(post))) {
        raw_list[[z]] <- data.table(
          panel_id = panel_id,
          group_col = group_col,
          K = as.integer(K),
          sample_id = sid,
          top_group = NA_character_,
          top_posterior = NA_real_,
          second_group = NA_character_,
          second_posterior = NA_real_,
          posterior_gap = NA_real_,
          n_snps_used = as.integer(n_used),
          confidence = "Low",
          status = "no_likelihood",
          note = "All likelihoods NA"
        )
        
        z <- z + 1L
        next
      }
      
      ord <- order(post, decreasing = TRUE)
      top1 <- ord[1]
      top2 <- if (length(ord) >= 2L) ord[2] else NA_integer_
      
      tg <- names(post)[top1]
      tp <- unname(post[top1])
      
      sg <- if (!is.na(top2)) names(post)[top2] else NA_character_
      sp <- if (!is.na(top2)) unname(post[top2]) else NA_real_
      
      gap <- if (!is.na(sp)) tp - sp else NA_real_
      
      conf <- conf_label(tp, high = high_thr, mod = mod_thr)
      
      st <- "ok"
      nt <- ""
      
      if (!is.na(gap) && gap < min_gap) {
        st <- "low_gap"
        nt <- paste0("posterior_gap<", min_gap)
      }
      
      raw_list[[z]] <- data.table(
        panel_id = panel_id,
        group_col = group_col,
        K = as.integer(K),
        sample_id = sid,
        top_group = tg,
        top_posterior = tp,
        second_group = sg,
        second_posterior = sp,
        posterior_gap = gap,
        n_snps_used = as.integer(n_used),
        confidence = conf,
        status = st,
        note = nt
      )
      
      z <- z + 1L
    }
  }
  
  raw_list <- raw_list[seq_len(z - 1L)]
  raw <- rbindlist(raw_list, fill = TRUE)
  
  stab <- raw[
    ,
    {
      dt_all <- .SD
      dt_ok <- .SD[status %in% c("ok", "low_gap") & !is.na(top_group)]
      
      nK_total <- length(unique(dt_all$K))
      nK <- length(unique(dt_ok$K))
      maxK_used <- if (nK > 0L) max(dt_ok$K) else NA_real_
      
      final_group <- if (!is.na(maxK_used)) {
        dt_ok[K == maxK_used][1, top_group]
      } else {
        NA_character_
      }
      
      agree <- if (!is.na(final_group) && nK > 0L) {
        mean(dt_ok$top_group == final_group)
      } else {
        NA_real_
      }
      
      stable_from_K <- stable_from_threshold(dt_ok[order(K)], final_group)
      
      tail_agree <- tail_agreement_with_final(
        dt = dt_ok,
        final_group = final_group,
        tail_fraction = tail_fraction
      )
      
      maxrow <- if (!is.na(maxK_used)) {
        dt_ok[K == maxK_used][1]
      } else {
        NULL
      }
      
      data.table(
        final_group = final_group,
        stable_from_K = as.numeric(stable_from_K),
        agreement_frac = as.numeric(agree),
        tail_agreement_frac = as.numeric(tail_agree),
        tail_fraction = as.numeric(tail_fraction),
        n_K_total_tested = as.integer(nK_total),
        n_K_usable_for_stability = as.integer(nK),
        n_K_available = as.integer(nK),
        maxK_used = as.numeric(maxK_used),
        maxK_top_posterior = if (!is.null(maxrow)) as.numeric(maxrow$top_posterior) else NA_real_,
        maxK_second_posterior = if (!is.null(maxrow)) as.numeric(maxrow$second_posterior) else NA_real_,
        maxK_gap = if (!is.null(maxrow)) as.numeric(maxrow$posterior_gap) else NA_real_,
        maxK_confidence = if (!is.null(maxrow)) as.character(maxrow$confidence) else NA_character_,
        maxK_status = if (!is.null(maxrow)) as.character(maxrow$status) else NA_character_,
        maxK_n_snps_used = if (!is.null(maxrow)) as.integer(maxrow$n_snps_used) else NA_integer_,
        status = if (nK > 0L) "ok" else "no_valid_K"
      )
    },
    by = .(panel_id, sample_id)
  ]
  
  list(raw = raw, stab = stab)
}

final_call <- function(
    stab_row,
    high_thr,
    mod_thr,
    min_gap,
    min_agreement,
    min_K,
    min_tail_agreement
) {
  if (is.null(stab_row) || nrow(stab_row) == 0L) {
    return(list(call = NA_character_, label = "Uncertain", reason = "no_result"))
  }
  
  s <- stab_row[1]
  
  if (!("final_group" %in% names(s)) || is.na(s$final_group)) {
    return(list(call = NA_character_, label = "Uncertain", reason = "no_final_group"))
  }
  
  if (is.na(s$maxK_n_snps_used) || s$maxK_n_snps_used <= 0) {
    return(list(call = NA_character_, label = "Uncertain", reason = "no_snps_used"))
  }
  
  p <- s$maxK_top_posterior
  gap <- s$maxK_gap
  
  if (is.na(p)) {
    return(list(call = NA_character_, label = "Uncertain", reason = "posterior_NA"))
  }
  
  conf <- conf_label(p, high = high_thr, mod = mod_thr)
  
  if (!(conf %in% c("High", "Moderate"))) {
    return(list(call = s$final_group, label = "Uncertain", reason = "low_posterior"))
  }
  
  if (!is.na(gap) && gap < min_gap) {
    return(list(call = s$final_group, label = "Uncertain", reason = paste0("gap<", min_gap)))
  }
  
  if (is.na(s$n_K_available) || s$n_K_available < min_K) {
    return(list(call = s$final_group, label = "Uncertain", reason = "too_few_usable_K"))
  }
  
  if (is.na(s$agreement_frac) || s$agreement_frac < min_agreement) {
    return(list(call = s$final_group, label = "Uncertain", reason = "low_global_K_agreement"))
  }
  
  if ("tail_agreement_frac" %in% names(s)) {
    if (is.na(s$tail_agreement_frac) || s$tail_agreement_frac < min_tail_agreement) {
      return(list(call = s$final_group, label = "Uncertain", reason = "unstable_large_K_tail"))
    }
  }
  
  list(call = s$final_group, label = conf, reason = "ok")
}

# =============================================================================
# Load inputs
# =============================================================================

meta_path <- file.path(opt$qc_dir, "metadata_clean.tsv")
panel_index_path <- file.path(opt$step3_dir, "panels_index.tsv")

if (!file.exists(meta_path)) {
  stop("Missing metadata_clean.tsv: ", meta_path, " (run Step 1-2 first)")
}

if (!file.exists(panel_index_path)) {
  stop("Missing panels_index.tsv: ", panel_index_path, " (run Step 3 first)")
}

meta <- fread(meta_path)
setnames(meta, tolower(names(meta)))

required_meta <- c("sample_id", "is_reference", "macroregion_3", "subregion")
missing_meta <- setdiff(required_meta, names(meta))

if (length(missing_meta) > 0L) {
  stop(
    "metadata_clean.tsv missing required column(s): ",
    paste(missing_meta, collapse = ", "),
    "\nFound: ",
    paste(names(meta), collapse = ", ")
  )
}

for (nm in names(meta)) {
  if (!inherits(meta[[nm]], c("numeric", "integer", "logical", "Date", "POSIXct"))) {
    meta[[nm]] <- clean_text(meta[[nm]])
  }
}

meta[, sample_id := clean_text(sample_id)]
meta[, is_reference := as_clean_logical(is_reference)]
meta[, macroregion_3 := clean_text(macroregion_3)]
meta[, subregion := clean_text(subregion)]

if ("country" %in% names(meta)) {
  meta[, country := clean_text(country)]
}

if ("population" %in% names(meta)) {
  meta[, population := clean_text(population)]
}

query_is_ref <- parse_bool1(
  opt$query_is_reference_value,
  default = FALSE,
  argname = "--query_is_reference_value"
)

query_ids <- meta[is_reference == query_is_ref, sample_id]

if (length(query_ids) == 0L) {
  stop("No query samples found with is_reference == ", query_is_ref)
}

message("Query samples: ", length(query_ids))

panels_index <- fread(panel_index_path)
setnames(panels_index, tolower(names(panels_index)))

required_pi <- c("panel_id", "panel_dir", "n_snps")
missing_pi <- setdiff(required_pi, names(panels_index))

if (length(missing_pi) > 0L) {
  stop("panels_index.tsv missing required column(s): ", paste(missing_pi, collapse = ", "))
}

get_panel_dir <- function(pid) {
  d <- panels_index[panel_id == pid, panel_dir]
  
  if (length(d) == 0L) return(NA_character_)
  
  d[1]
}

fix_panel_dir <- function(d) {
  if (is.na(d)) return(d)
  if (dir.exists(d)) return(d)
  
  d2 <- file.path(opt$step3_dir, d)
  if (dir.exists(d2)) return(d2)
  
  d3 <- file.path(opt$step3_dir, "panels", basename(d))
  if (dir.exists(d3)) return(d3)
  
  d
}

p1_id <- "P1_macroregion_africa_vs_asia"
p2_id <- "P2_subregion_within_africa"
p3_id <- "P3_subregion_within_asia"

p1_dir <- fix_panel_dir(get_panel_dir(p1_id))
p2_dir <- fix_panel_dir(get_panel_dir(p2_id))
p3_dir <- fix_panel_dir(get_panel_dir(p3_id))

if (is.na(p1_dir) || !dir.exists(p1_dir)) {
  stop("Cannot find panel directory for ", p1_id, ": ", p1_dir)
}

if (is.na(p2_dir) || !dir.exists(p2_dir)) {
  stop("Cannot find panel directory for ", p2_id, ": ", p2_dir)
}

if (is.na(p3_dir) || !dir.exists(p3_dir)) {
  stop("Cannot find panel directory for ", p3_id, ": ", p3_dir)
}

panel_nsnps <- function(panel_dir) {
  sm <- file.path(panel_dir, "snp_map.tsv")
  sx <- file.path(panel_dir, "snp_matrix.rds")
  
  if (file.exists(sm)) return(nrow(fread(sm)))
  if (file.exists(sx)) return(nrow(readRDS(sx)))
  
  0L
}

# =============================================================================
# Build K grids
# =============================================================================

baseK <- parse_integer_vector(opt$base_K)
extraK <- parse_integer_vector(opt$extra_K)

auto_extend_K <- parse_bool1(
  opt$auto_extend_K,
  default = TRUE,
  argname = "--auto_extend_K"
)

include_all_snps_K <- parse_bool1(
  opt$include_all_snps_K,
  default = TRUE,
  argname = "--include_all_snps_K"
)

p1_n <- panel_nsnps(p1_dir)
p2_n <- panel_nsnps(p2_dir)
p3_n <- panel_nsnps(p3_dir)

Ks_p1 <- make_Ks(
  n_snps = p1_n,
  baseK = baseK,
  extraK = extraK,
  auto_extend = auto_extend_K,
  include_all = include_all_snps_K,
  max_points = opt$max_K_points
)

Ks_p2 <- make_Ks(
  n_snps = p2_n,
  baseK = baseK,
  extraK = extraK,
  auto_extend = auto_extend_K,
  include_all = include_all_snps_K,
  max_points = opt$max_K_points
)

Ks_p3 <- make_Ks(
  n_snps = p3_n,
  baseK = baseK,
  extraK = extraK,
  auto_extend = auto_extend_K,
  include_all = include_all_snps_K,
  max_points = opt$max_K_points
)

message("P1 SNPs: ", p1_n, " | K grid: ", paste(Ks_p1, collapse = ", "))
message("P2 SNPs: ", p2_n, " | K grid: ", paste(Ks_p2, collapse = ", "))
message("P3 SNPs: ", p3_n, " | K grid: ", paste(Ks_p3, collapse = ", "))

K_grid_used <- data.table(
  panel_id = c(
    rep(p1_id, length(Ks_p1)),
    rep(p2_id, length(Ks_p2)),
    rep(p3_id, length(Ks_p3))
  ),
  n_snps_available = c(
    rep(p1_n, length(Ks_p1)),
    rep(p2_n, length(Ks_p2)),
    rep(p3_n, length(Ks_p3))
  ),
  K = c(Ks_p1, Ks_p2, Ks_p3)
)

fwrite(
  K_grid_used,
  file.path(opt$out_dir, "step4_K_grid_used.tsv"),
  sep = "\t"
)

saveRDS(
  K_grid_used,
  file.path(opt$out_dir, "step4_K_grid_used.rds")
)

# =============================================================================
# Run P1 macroregion assignment
# =============================================================================

message("\nRunning P1 macroregion assignment...")

p1 <- assign_panel_multiK(
  panel_id = p1_id,
  panel_dir = p1_dir,
  group_col = "macroregion_3",
  meta = meta,
  query_ids = query_ids,
  Ks = Ks_p1,
  pseudocount = opt$pseudocount,
  epsilon = opt$epsilon,
  min_snps_query = opt$min_snps_query_macroregion,
  high_thr = opt$high_posterior,
  mod_thr = opt$moderate_posterior,
  min_gap = opt$min_gap_macroregion,
  tail_fraction = opt$tail_fraction
)

if (!("sample_id" %in% names(p1$stab))) {
  stop("P1 produced no per-sample stability table. Check P1 panel files.")
}

p1_call <- p1$stab[
  ,
  {
    fc <- final_call(
      .SD,
      high_thr = opt$high_posterior,
      mod_thr = opt$moderate_posterior,
      min_gap = opt$min_gap_macroregion,
      min_agreement = opt$min_agreement,
      min_K = opt$min_K_available,
      min_tail_agreement = opt$min_tail_agreement
    )
    
    data.table(
      macroregion_call = fc$call,
      macroregion_confidence = fc$label,
      macroregion_reason = fc$reason,
      macroregion_maxK_used = maxK_used,
      macroregion_maxK_post = maxK_top_posterior,
      macroregion_maxK_gap = maxK_gap,
      macroregion_agreement = agreement_frac,
      macroregion_tail_agreement = tail_agreement_frac,
      macroregion_tail_fraction = tail_fraction,
      macroregion_stable_from_K = stable_from_K,
      macroregion_nK = n_K_available,
      macroregion_nK_total_tested = n_K_total_tested,
      macroregion_nK_usable_for_stability = n_K_usable_for_stability,
      macroregion_maxK_nsnps = maxK_n_snps_used
    )
  },
  by = sample_id
]

# =============================================================================
# Conditional P2/P3 subregion assignment
# =============================================================================

africa_q <- p1_call[
  macroregion_call == "Africa" & macroregion_confidence %in% c("High", "Moderate"),
  sample_id
]

asia_q <- p1_call[
  macroregion_call == "Asia" & macroregion_confidence %in% c("High", "Moderate"),
  sample_id
]

message("\nSubregion assignment attempted for:")
message("  Africa confident queries: ", length(africa_q))
message("  Asia confident queries:   ", length(asia_q))

message("\nRunning P2 Africa subregion assignment...")

p2 <- assign_panel_multiK(
  panel_id = p2_id,
  panel_dir = p2_dir,
  group_col = "subregion",
  meta = meta,
  query_ids = africa_q,
  Ks = Ks_p2,
  pseudocount = opt$pseudocount,
  epsilon = opt$epsilon,
  min_snps_query = opt$min_snps_query_subregion,
  high_thr = opt$high_posterior,
  mod_thr = opt$moderate_posterior,
  min_gap = opt$min_gap_subregion,
  tail_fraction = opt$tail_fraction
)

message("\nRunning P3 Asia subregion assignment...")

p3 <- assign_panel_multiK(
  panel_id = p3_id,
  panel_dir = p3_dir,
  group_col = "subregion",
  meta = meta,
  query_ids = asia_q,
  Ks = Ks_p3,
  pseudocount = opt$pseudocount,
  epsilon = opt$epsilon,
  min_snps_query = opt$min_snps_query_subregion,
  high_thr = opt$high_posterior,
  mod_thr = opt$moderate_posterior,
  min_gap = opt$min_gap_subregion,
  tail_fraction = opt$tail_fraction
)

make_sub_call <- function(stab, panel_label) {
  if (is.null(stab) || nrow(stab) == 0L || !("sample_id" %in% names(stab))) {
    return(data.table(
      sample_id = character(),
      subregion_call = character(),
      subregion_confidence = character(),
      subregion_reason = character(),
      subregion_panel = character(),
      subregion_maxK_used = numeric(),
      subregion_maxK_post = numeric(),
      subregion_maxK_gap = numeric(),
      subregion_agreement = numeric(),
      subregion_tail_agreement = numeric(),
      subregion_tail_fraction = numeric(),
      subregion_stable_from_K = numeric(),
      subregion_nK = integer(),
      subregion_nK_total_tested = integer(),
      subregion_nK_usable_for_stability = integer(),
      subregion_maxK_nsnps = integer()
    ))
  }
  
  stab[
    ,
    {
      fc <- final_call(
        .SD,
        high_thr = opt$high_posterior,
        mod_thr = opt$moderate_posterior,
        min_gap = opt$min_gap_subregion,
        min_agreement = opt$min_agreement,
        min_K = opt$min_K_available,
        min_tail_agreement = opt$min_tail_agreement
      )
      
      data.table(
        subregion_call = fc$call,
        subregion_confidence = fc$label,
        subregion_reason = fc$reason,
        subregion_panel = panel_label,
        subregion_maxK_used = maxK_used,
        subregion_maxK_post = maxK_top_posterior,
        subregion_maxK_gap = maxK_gap,
        subregion_agreement = agreement_frac,
        subregion_tail_agreement = tail_agreement_frac,
        subregion_tail_fraction = tail_fraction,
        subregion_stable_from_K = stable_from_K,
        subregion_nK = n_K_available,
        subregion_nK_total_tested = n_K_total_tested,
        subregion_nK_usable_for_stability = n_K_usable_for_stability,
        subregion_maxK_nsnps = maxK_n_snps_used
      )
    },
    by = sample_id
  ]
}

p2_call <- make_sub_call(p2$stab, "P2_Africa")
p3_call <- make_sub_call(p3$stab, "P3_Asia")

sub_call <- rbindlist(list(p2_call, p3_call), fill = TRUE)

# =============================================================================
# Final assignment table
# =============================================================================

final <- merge(p1_call, sub_call, by = "sample_id", all.x = TRUE)

final[
  !(macroregion_confidence %in% c("High", "Moderate")),
  `:=`(
    subregion_call = NA_character_,
    subregion_confidence = "Uncertain",
    subregion_reason = "macroregion_uncertain",
    subregion_panel = NA_character_
  )
]

final[
  macroregion_confidence %in% c("High", "Moderate") & is.na(subregion_confidence),
  `:=`(
    subregion_confidence = "Uncertain",
    subregion_reason = "subregion_not_attempted_or_no_result"
  )
]

add_cols <- intersect(
  c("country", "population", "macroregion_3", "subregion", "is_reference"),
  names(meta)
)

meta_min <- unique(meta[, c("sample_id", add_cols), with = FALSE])

final <- merge(final, meta_min, by = "sample_id", all.x = TRUE)

setorder(final, sample_id)

# =============================================================================
# Write TSV/RDS outputs
# =============================================================================

fwrite(final, file.path(opt$out_dir, "final_assignment.tsv"), sep = "\t")
saveRDS(final, file.path(opt$out_dir, "final_assignment.rds"))

fwrite(p1$raw, file.path(opt$out_dir, "P1_macroregion_raw.tsv"), sep = "\t")
saveRDS(p1$raw, file.path(opt$out_dir, "P1_macroregion_raw.rds"))

fwrite(p1$stab, file.path(opt$out_dir, "P1_macroregion_stability.tsv"), sep = "\t")
saveRDS(p1$stab, file.path(opt$out_dir, "P1_macroregion_stability.rds"))

fwrite(p2$raw, file.path(opt$out_dir, "P2_africa_subregion_raw.tsv"), sep = "\t")
saveRDS(p2$raw, file.path(opt$out_dir, "P2_africa_subregion_raw.rds"))

fwrite(p2$stab, file.path(opt$out_dir, "P2_africa_subregion_stability.tsv"), sep = "\t")
saveRDS(p2$stab, file.path(opt$out_dir, "P2_africa_subregion_stability.rds"))

fwrite(p3$raw, file.path(opt$out_dir, "P3_asia_subregion_raw.tsv"), sep = "\t")
saveRDS(p3$raw, file.path(opt$out_dir, "P3_asia_subregion_raw.rds"))

fwrite(p3$stab, file.path(opt$out_dir, "P3_asia_subregion_stability.tsv"), sep = "\t")
saveRDS(p3$stab, file.path(opt$out_dir, "P3_asia_subregion_stability.rds"))

params <- data.table(
  parameter = names(opt),
  value = vapply(opt, function(x) paste(x, collapse = ","), character(1))
)

params <- rbind(
  params,
  data.table(parameter = "baseK_parsed", value = paste(baseK, collapse = ",")),
  data.table(parameter = "extraK_parsed", value = paste(extraK, collapse = ",")),
  data.table(parameter = "auto_extend_K_parsed", value = as.character(auto_extend_K)),
  data.table(parameter = "include_all_snps_K_parsed", value = as.character(include_all_snps_K))
)

fwrite(params, file.path(opt$out_dir, "step4_params.tsv"), sep = "\t")
saveRDS(params, file.path(opt$out_dir, "step4_params.rds"))

run_info <- list(
  step = "step4_multilevel_assignment",
  repo_root = repo_root,
  qc_dir = opt$qc_dir,
  step3_dir = opt$step3_dir,
  out_dir = opt$out_dir,
  n_query_samples = length(query_ids),
  p1_n_snps = p1_n,
  p2_n_snps = p2_n,
  p3_n_snps = p3_n,
  baseK = baseK,
  extraK = extraK,
  auto_extend_K = auto_extend_K,
  include_all_snps_K = include_all_snps_K,
  Ks_p1 = Ks_p1,
  Ks_p2 = Ks_p2,
  Ks_p3 = Ks_p3,
  K_grid_used = K_grid_used,
  min_snps_query_macroregion = opt$min_snps_query_macroregion,
  min_snps_query_subregion = opt$min_snps_query_subregion,
  min_agreement = opt$min_agreement,
  min_K_available = opt$min_K_available,
  tail_fraction = opt$tail_fraction,
  min_tail_agreement = opt$min_tail_agreement,
  parameters = opt,
  timestamp = Sys.time(),
  session_info = sessionInfo()
)

saveRDS(run_info, file.path(opt$out_dir, "step4_run_info.rds"))

# =============================================================================
# Write Excel workbook
# =============================================================================

out_file <- file.path(opt$out_dir, opt$out_xlsx)

wb <- createWorkbook()

sn_final <- safe_sheet(wb, "FINAL_macro_sub")
addWorksheet(wb, sn_final)
writeDataTable(wb, sn_final, final)

sn_kgrid <- safe_sheet(wb, "K_GRID_USED")
addWorksheet(wb, sn_kgrid)
writeDataTable(wb, sn_kgrid, K_grid_used)

sn_p1_raw <- safe_sheet(wb, "P1_macro_raw")
addWorksheet(wb, sn_p1_raw)
writeDataTable(wb, sn_p1_raw, p1$raw)

sn_p1_stab <- safe_sheet(wb, "P1_macro_stab")
addWorksheet(wb, sn_p1_stab)
writeDataTable(wb, sn_p1_stab, p1$stab)

sn_p2_raw <- safe_sheet(wb, "P2_AFR_sub_raw")
addWorksheet(wb, sn_p2_raw)
writeDataTable(wb, sn_p2_raw, p2$raw)

sn_p2_stab <- safe_sheet(wb, "P2_AFR_sub_stab")
addWorksheet(wb, sn_p2_stab)
writeDataTable(wb, sn_p2_stab, p2$stab)

sn_p3_raw <- safe_sheet(wb, "P3_ASIA_sub_raw")
addWorksheet(wb, sn_p3_raw)
writeDataTable(wb, sn_p3_raw, p3$raw)

sn_p3_stab <- safe_sheet(wb, "P3_ASIA_sub_stab")
addWorksheet(wb, sn_p3_stab)
writeDataTable(wb, sn_p3_stab, p3$stab)

sn_params <- safe_sheet(wb, "PARAMS")
addWorksheet(wb, sn_params)
writeDataTable(wb, sn_params, params)

saveWorkbook(wb, out_file, overwrite = TRUE)

# =============================================================================
# Final messages
# =============================================================================

message("\nDone.")
message("Final assignment TSV: ", file.path(opt$out_dir, "final_assignment.tsv"))
message("Final assignment RDS: ", file.path(opt$out_dir, "final_assignment.rds"))
message("K grid used:          ", file.path(opt$out_dir, "step4_K_grid_used.tsv"))
message("Excel workbook:       ", out_file)